# This is a basic workflow to help you get started with Actions

name: deploy

on:
  workflow_call:
    inputs:
      ENVIRONMENT:
        required: true
        type: string
    secrets:
      AZURE_CREDENTIALS:
         required: true    

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: 
      name: ${{ inputs.ENVIRONMENT }}
    steps:
      - uses: actions/checkout@v3
      
      - name: echoEnv
        run: echo "Env is ${{ inputs.ENVIRONMENT }}"

      - name: Sign in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: create RG
        uses: azure/cli@v1
        with: 
          inlineScript: az group create -n ${{ env.Az_RG_Name }} -l 'WestEurope'

