# This is a basic workflow to help you get started with Actions

name: Deploy to Env

# Controls when the workflow will run
on:
  workflow_dispatch:


jobs:
  deploy-test:    
    runs-on: ubuntu-latest
    environment: DEV
    env: 
      Az_RG_Name: gitops6_dev
    steps:
      - uses: actions/checkout@v3
      
      - name: Sign in to Azure
        uses: azure/login@v1
        with:
          creds: ${{secrets.AZURE_CREDENTIALS_TEST}}

      - name: create RG
        uses: azure/cli@v1
        with: 
          inlineScript: az group create -n ${{env.Az_RG_Name}} -l 'WestEurope'
    
  deploy-prod:    
    runs-on: ubuntu-latest
    environment: PROD
    needs: deploy-test
    env: 
      Az_RG_Name: gitops6_prod
    steps:
      - uses: actions/checkout@v3
      
      - name: Sign in to Azure
        uses: azure/login@v1
        with:
          creds: ${{secrets.AZURE_CREDENTIALS_PROD}}

      - name: create RG
        uses: azure/cli@v1
        with: 
          inlineScript: az group create -n ${{env.Az_RG_Name}} -l 'WestEurope'